name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        with:
          github_user_name: mohsinkhan117
          svg_out_path: dist/snake.svg
          
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: output
          folder: dist
