name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mohsinkhan117
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Generate Snake (Dark Mode)
        uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: mohsinkhan117
          gif_out_path: dist/github-contribution-grid-snake-dark.gif
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}